[package]
name = "hyper-staticfile"
version = "0.1.0"
authors = [
  "Zach Pomerantz <zmp@umich.edu>",
  "Jonathan Reem <jonathan.reem@gmail.com>",
  "Stéphan Kochen <stephan@kochen.nl>",
]
description = "Static file serving for Hyper 0.11"
repository = "https://github.com/stephank/hyper-staticfile"
license = "MIT"
keywords = ["hyper", "web", "http", "file"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
url = "1.1"

[dev-dependencies]
tempdir = "0.3"
