[package]
name = "hyper-staticfile"
version = "0.1.1"
authors = [
  "Zach Pomerantz <zmp@umich.edu>",
  "Jonathan Reem <jonathan.reem@gmail.com>",
  "Stéphan Kochen <stephan@kochen.nl>",
]
description = "Static file serving for Hyper 0.11"
repository = "https://github.com/stephank/hyper-staticfile"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/hyper-staticfile"
keywords = ["hyper", "web", "http", "file", "static"]
categories = ["web-programming::http-server"]

[dependencies]
futures = "0.1.21"
hyper = "0.11.25"
tokio = "0.1.5"
url = "1.7.0"

[dev-dependencies]
tempdir = "0.3.7"
